In [1]:
import numpy as np


In [2]:
v = np.array([1,-1,2])
w = np.array([2,5,2])


In [3]:
print(v+w)

[3 4 4]


In [4]:
print(v-w)

[-1 -6  0]


In [5]:
#Scalar Multiplication
print(3*w)

[ 6 15  6]


In [6]:
#Calculating the length of the vector
print(np.linalg.norm(v))

2.449489742783178


In [ ]:
s= 